version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
              - unique
                  
    - name: demo_model
      description: "Total purchase for each customer in snowflake"
      columns:
        - name: c_custkey
          tests:
            - not_null

    - name: cumulative_orders_by_date
    
    - name: dates

    - name: incremental_time

    - name: dates1

    - name: playing_with_tests
      description: "Playing with test using customer data from snowflake"
      columns:
        - name: c_custkey

        - name: mktsegment
          accepted_values:
            values: ['BUILDING', 'AUTOMOBILE', 'MACHINERY', 'HOUSEHOLD', 'FURNITURE']

sources:
  - name: sample
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: customer
        columns:
          - name: c_custkey
            tests:
              - unique
              - not_null
      - name: orders